version: "3.3"
services:
  haproxy:
    image: haproxy:latest
    ports:
      - "8080:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
  webapp:
    image: hello-world
    deploy:
      replicas: 3
networks:
  proxy:
    external: true